---
- hosts: all
  become: true
  tasks:
    - name: ensure packages required are installed
      yum: pkg={{ item }} state=latest
      with_items:
        - libaio
        - bc
        - flex
        - unzip
        - python
    - name: create Splunk user
      user: name=splunk uid=1000 home=/home/splunk state=present
    - name: extract Splunk Enterprise
      command: tar zxf /vagrant/splunk/Splunk-Latest.tgz
      args:
        chdir: /usr/local
        creates: /usr/local/splunk
    - name: set Splunk shell env
      shell: echo '. /usr/local/splunk/bin/setSplunkEnv' >> /home/splunk/.bash_profile
      become_user: splunk
    - name: set ip tables
      shell: iptables -I INPUT 5 -p tcp -j ACCEPT --dport 8000
    - name: start splunk server
      shell:  "/usr/local/splunk/bin/splunk start --accept-license --answer-yes"
      become_user: splunk
    - name: enable Splunk boot init script
      command: /usr/local/splunk/bin/splunk enable boot-start -user splunk
