---
- hosts: all
  become: true
  tasks:
    - name: ensure packages required are installed
      yum: pkg={{ item }} state=latest
      with_items:
        - libaio
        - bc
        - flex
        - unzip
        - python
    - name: create Splunk user
      user: name=splunk uid=1001 home=/home/splunk state=present
    - name: Download Splunk Enterpise
      get_url:
        url: https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=7.2.3&product=splunk&filename=splunk-7.2.3-06d57c595b80-Linux-x86_64.tgz&wget=true
        checksum: md5:ac6f332dc37845e5d68516233cf8dc8e
        dest: /vagrant/Splunk.tgz
    - name: extract Splunk Enterprise
      unarchive:
        src: /vagrant/Splunk.tgz
        remote_src: yes
        dest: /usr/local
        owner: splunk
        creates: /usr/local/splunk/README-splunk.txt
    - name: set Splunk free disk space
      shell: echo '
          [diskUsage]
          minFreeSpace = 500' >> /usr/local/splunk/etc/system/local/server.conf
    - name: setup admin user
      copy:
          src: user-seed.conf
          dest: /usr/local/splunk/etc/system/local/user-seed.conf
          owner: splunk
    - name: set Splunk shell env
      shell: echo '. /usr/local/splunk/bin/setSplunkEnv' >> /home/splunk/.bash_profile
      become_user: splunk
    - name: set iptables
      shell: iptables -A INPUT -p tcp -j ACCEPT --dport 8000
    - name: save iptables
      shell: iptables-save >| /etc/sysconfig/iptables
    - name: start splunk server
      shell:  "/usr/local/splunk/bin/splunk start --accept-license --answer-yes"
      become_user: splunk
    - name: enable Splunk boot init script
      command: /usr/local/splunk/bin/splunk enable boot-start -user splunk
